### PR TITLE
Parse buffer and custom IO

### PR DESCRIPTION
**Pull request by greg-sokol**
Hi Ben,

I happen to have been using your code for some time now and it works great. Today i faced a problem - I got my ini file in an encrypted form. After decrypting I have the file stored in a memory buffer and I realized that there was no API in inih to parse a buffer. So I added the code to handle such cases.
With a bit of extra coding I extended the API to handle any custom IO (like sockets for example).
Please feel free to review my changes and share your opionion. I'm pretty new to github so I assumed a pull request would be a nice way to share my changes.
Regards
Greg

### CODE REVIEW

**Comment by benhoyt** [comment]
Hi @greg-sokol, thanks for that. I like the idea here, of passing in a function in place of `fgets`. I'd like to enable this, however, I'd rather not include the actual buffer reading code (`ini_buffer_getln`) in the library itself. So I'm going to have a shot at this in the next week or so and I'll post an update here.

**Comment by greg-sokol** [comment]
Hi Ben,

thanks for quick feedback. Indeed, the bit of code for reading buffer doesn't look clean even to me. I have a feeling that, if not thrown away, it could go to the 'examples' dir as an illustration how custom IO could be implemented.
I've been doing some embedded development and sometimes it's desirable to substitute the system IO with custom implementation. This often happens on bare metal, resource scarce systems.

Thanks again, have a good day.
Greg

**Comment by benhoyt** [comment]
Hi Greg, I've added `ini_parse_stream()` in https://github.com/benhoyt/inih/commit/a5896a47c5cd79dd631bb33fc8c6b356eb0a92a6 -- please review. That include examples/ini_buffer.c, an example with your buffer-reading function copied directly (thanks!).

I've also added a small paragraph about the alternative `ini_parse_*` functions in the README, and a link to that example program.

**Comment by greg-sokol** [comment]
Excellent,
thanks.

**Comment by benhoyt** [comment]
Cool. I've added a new release https://github.com/benhoyt/inih/releases/tag/r32 which includes this.

**Pull request closed without merging**
