### PR TITLE
fix parsing '#' comments in the middle of a line

### PR DESCRIPTION
**Pull request by M1cha**

### CODE REVIEW

**Comment by benhoyt** [comment]
Per https://github.com/benhoyt/inih/issues/40, I'm actually about to disable inline comments by default (you'll be able to enable them with -DINI_ALLOW_INLINE_COMMENTS, which will enable the behaviour of your fix). This is in line with the current (Python 3.2+) defaults, and the handling of inline comments is a bit weird anyway -- probably why Python changed their defaults, see [here](https://docs.python.org/3/whatsnew/3.2.html#configparser).

Sound okay?

**Comment by benhoyt** [comment]
Actually, on seconds thoughts, I think I'll leave inline comments with only ';' as the default to preserve `inih` backwards compatibility behaviour. Users will still be able to easily disable with `-DDINI_ALLOW_INLINE_COMMENTS=)`, or enable your patch's behaviour with `-DINI_INLINE_COMMENT_PREFIXES=";#"`.

**Comment by benhoyt** [comment]
This is now done in release [r34](https://github.com/benhoyt/inih/releases/tag/r34).

**Comment by benhoyt** [comment]
Oops, make that [r35](https://github.com/benhoyt/inih/releases/tag/r35) -- there was a small bug in r34 where it always override your `INI_INLINE_COMMENT_PREFIXES`.

**Comment by M1cha** [comment]
thx :)
btw shouldn't all parsing related defines be replaced with runtime configuration so u could parse different files with different behavior?

**Comment by benhoyt** [comment]
Well, if this was a full-featured inih library, yes, but inih is "simple, good for embedded systems", so all the settings are global and compile time to keep things simple and the runtime footprint tiny.

**Pull request closed without merging**
