### PR TITLE
Memory usage optimization

### PR DESCRIPTION
**Pull request by artemShelest**
Use references instead of copying strings. INIReader object is actually const afer construction, so I reflected this in the code as well.

### CODE REVIEW

**Comment by benhoyt** [comment]
Thanks for taking the time to write a PR. Someone actually submitted something very similar to this, and the short version is I'm not sure it's an improvement or that I want to work on the C++ wrapper of inih; I'd rather focus on the C version (I know C well enough to maintain effectively :-). Please read the commentary at https://github.com/benhoyt/inih/pull/42 and let me know if you have further thoughts.

**Comment by artemShelest** [comment]
Hi,
Thank you for your reply.
I believe that modern C++ compilers are capable to make all these
optimizations that have been done in this PR.
I was surprised to see stl strings instead of const char* in this lib. For
my application, using std::string is ok, but for the sake of simplicity I'd
rewrite the whole c++ stuff in this lib using const char*.
The one thing that is beyond #42 is const-correctness - it should be
maintained, regardless of having or not having refs.


2016-04-16 19:15 GMT+03:00 Ben Hoyt <notifications@github.com>:

**Comment by benhoyt** [comment]
Well, `const char*` is not safe, idiomatic C++ -- if you want the `const char*` version, just use the inih C library.

In any case, I agree with your assessment above about const correctness -- I'm going to close this PR, but if you want to submit a new one with just the `const`s after the function definitions for ParseError and the Get* functions, I'd be happy to merge that.

**Comment by artemShelest** [comment]
Agree on the safe code. New PR is out.
Thank you.

2016-04-17 4:06 GMT+03:00 Ben Hoyt <notifications@github.com>:

**Pull request closed without merging**
