### PR TITLE
[fuzzing] making things simple

### PR DESCRIPTION
**Pull request by 0x34d**
Removed the old fuzz testing build with AFL, using libfuzzer as the main fuzzer.
I did not try to overcomplicate the fuzzing.sh, it's a little copy-pasta but looks nice and simple.
I have updated the fuzzing target to `ini_parse_string` for more code coverage.

### CODE REVIEW

**Comment by benhoyt** [comment]
I'm sorry if the recent XZ attack has spoiled things for us, but without looking too closely at your change, I'm highly unlikely to merge a PR without context or motivation from someone who's GitHub tagline is "Professional backdoor shipper for memes"...

**Comment by 0x34d** [comment]
> I'm sorry if the recent XZ attack has spoiled things for us, but without looking too closely at your change, I'm highly unlikely to merge a PR without context or motivation from someone who's GitHub tagline is "Professional backdoor shipper for memes"...

No, no no, that was for fun, because of `XZ` backdoor;

**Comment by benhoyt** [comment]
I think the joke is in pretty poor taste -- assuming you're a legitimate contributor, it makes you look like a troll. "Too soon", as they say.

What's the motivation for this change or the context of why it's needed?

**Comment by 0x34d** [comment]
> I think the joke is in pretty poor taste -- assuming you're a legitimate contributor, it makes you look like a troll. "Too soon", as they say.

I'm sorry, dude, it was funny though.

>  What's the motivation for this change or the context of why it's needed?


Ah, I was trying to understand [oss-fuzz-gen](https://github.com/google/oss-fuzz-gen), then I saw [inih](https://github.com/google/oss-fuzz-gen?tab=readme-ov-file#current-top-coverage-improvements-by-project) and found out `ini_parse_string` is increasing the code coverage.

I deleted some of the old files to make things easier, removed the AFL build, and started using libFuzzer as the official fuzzer. AFL++ does support libFuzzer code with their own libAFLDriver.a library.

**Comment by 0x34d** [comment]
Don't merge now;

**Comment by benhoyt** [comment]
@0x34d It looked like your account and all your PRs were deleted for a few days? What was going on?

**Comment by 0x34d** [comment]
> @0x34d It looked like your account and all your PRs were deleted for a few days? What was going on?

Well, that lame joke was a little heavy for the GitHub system, and I got suspended. I will try my best not to do that again.
Then I was flagged.

**Comment by 0x34d** [comment]
Note: I just need a little time to figure things out; after that, I will reopen this.

**Pull request closed without merging**
