### PR TITLE
[fuzzing] Updated the workflow and tried to simplify the OSS-fuzz and local fuzzing build.

### PR DESCRIPTION
**Pull request by pkillarjun**
* Updated workflow to use all three sanitizers [address, undefined, memory];
*  Update the target under test to `ini_parse_string` from `ini_parse` for better coverage and ease of use and understanding.
* Removed AFL fuzzer build and use only standard libFuzzer. Note, if you like to build with AFL++, you can use AFL++ official `libAFLDriver.a` library for libFuzzer targets.
* After this PR merge, I will remove the `build.sh` from the official oss-fuzz repo and use `oss-fuzz.sh` for compilation in the oss-fuzz infrastructure.

Hey Benhoyt,
I will use this account to maintain all my OSS-Fuzz integrated projects.

### CODE REVIEW

**Comment by 0x34d** [comment]
Comment for Verification;

**Comment by pkillarjun** [comment]
Everything is working as expected https://github.com/google/oss-fuzz/actions/runs/8821238582

**Comment by benhoyt** [comment]
Hi @pkillarjun -- thanks for the contribution. I've thought about this further, and decided I don't have the time or knowledge to properly review OSS-Fuzz scripts and PRs. In addition, the `0x34d` "Professional backdoor shipper" joke turned me off a bit. So I'm going to remove the OSS-Fuzz support from this repo. You're welcome to fork inih and add OSS-Fuzz support in your fork. I'm sorry about that!

**Comment by pkillarjun** [comment]
Well, I never dreamed of this response and https://github.com/benhoyt/inih/pull/169.

**Comment by pkillarjun** [comment]
> You're welcome to fork inih and add OSS-Fuzz support in your fork. I'm sorry about that!

I hope you are okay with these changes?
https://github.com/google/oss-fuzz/pull/11836
https://github.com/pkillarjun/oss-fuzz-src/commit/2f680c1722f8d0ce5731ee8defaa78e748c3049f

**Comment by benhoyt** [comment]
I know it's not what you we're hoping for. But I appreciate you moving the oss-fuzz stuff to a fork. Those changes look reasonable to me!

**Comment by pkillarjun** [comment]
> I know it's not what you we're hoping for. But I appreciate you moving the oss-fuzz stuff to a fork. Those changes look reasonable to me!

I understand your thoughts on forks, but OSS-Fuzz does not accept forks of some random dude on the internet,
Don't worry, I will be managing this.

**Comment by DonggeLiu** [comment]
Hi @benhoyt, I am a maintainer of OSS-Fuzz.
May I double-check if you are still interested in using the OSS-Fuzz service (fuzzing `inih`, receiving reports, etc.)?
Thanks!

Just want to ensure that I understand the situation correctly : )

**Comment by pkillarjun** [comment]
If Ben Hoyt agrees, I will proceed with this one, not the current PR.

- https://github.com/google/oss-fuzz/pull/11836
- https://github.com/pkillarjun/oss-fuzz-src/commit/2f680c1722f8d0ce5731ee8defaa78e748c3049f

**Comment by benhoyt** [comment]
@DonggeLiu I don't mind if someone else uses the OSS-Fuzz service to fuzz inih, and I'm happy to receive real bug reports, but I'd rather not maintain the fuzz code and scripts anymore in my inih repo.

**Comment by DonggeLiu** [comment]
Thanks for the confirmation, @benhoyt.

**Pull request closed without merging**
