### PR TITLE
[Fuzzing] using cifuzz for PR

### PR DESCRIPTION
**Pull request by 0x34d**
using [cifuzz](https://google.github.io/oss-fuzz/getting-started/continuous-integration) for fuzzing PR.

### CODE REVIEW

**Comment by benhoyt** [comment]
@0x34d Could you please describe the PR in a bit more detail? Specifically, does the building and fuzzing run happen on Google's servers? Will it just run for 5 minutes and then stop?

What happens on failure? Can we introduce a failure temporarily to test that? What is "SARIF", and where is it uploaded?

**Comment by benhoyt** [comment]
Hmmm, I'm not sure what I'm signing up for here. Will I need to start interpreting and fixing fuzz test cases, like the one that I was just emailed? https://oss-fuzz.com/testcase-detail/5200064623280128

I like the idea of fuzzing, but I have limited time to decipher and analyse. Maybe (if you're keen on this), it is better to do this based on your fork, and then you can submit bug-fix PRs to my repo if you like.

**Comment by 0x34d** [comment]
> Hmmm, I'm not sure what I'm signing up for here. 

Well, it's actually complicated.

> Will I need to start interpreting and fixing fuzz test cases, like the one that I was just emailed? https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=60878 and https://oss-fuzz.com/testcase-detail/5200064623280128

DONE: https://github.com/benhoyt/inih/pull/156 

> I like the idea of fuzzing, but I have limited time to decipher and analyse. Maybe (if you're keen on this), it is better to do this based on your fork, and then you can submit bug-fix PRs to my repo if you like.

They have a 90-day timeline. Right now, I'm working on a private project audit. You, I, or anyone else(after 90 days) can fix those bugs.


And if you don't like the idea of PR-fuzzing, you can close this PR.

**Comment by benhoyt** [comment]
Sure, why not. I can try it for a while, at any rate.

**Pull request merged**
